<?php
/** Template Name: SEEF About */
get_header();
?>
<main id="main" class="site-main">
	<section class="seef-page-hero"><div class="seef-shell"><p class="seef-eyebrow"><?php esc_html_e( 'À propos de SEEF STORE', 'seef-store' ); ?></p><h1><?php esc_html_e( 'Le beau devient utile.', 'seef-store' ); ?><br><?php esc_html_e( 'L’utile devient évident.', 'seef-store' ); ?></h1><p><?php esc_html_e( 'Une sélection contemporaine qui place la simplicité, la qualité d’usage et la clarté au premier plan.', 'seef-store' ); ?></p></div></section>
	<section class="seef-section"><div class="seef-shell seef-story-grid" data-reveal><div><p class="seef-eyebrow">01 — <?php esc_html_e( 'Notre histoire', 'seef-store' ); ?></p><h2><?php esc_html_e( 'Une sélection née du refus du superflu.', 'seef-store' ); ?></h2></div><div><p><?php esc_html_e( 'SEEF STORE imagine une autre façon de découvrir les objets du quotidien : moins de références interchangeables, plus de cohérence et une information honnête.', 'seef-store' ); ?></p><p><?php esc_html_e( 'Cette vitrine portfolio met en scène une marque fictive dans une expérience e-commerce complète, du catalogue au suivi des commandes.', 'seef-store' ); ?></p></div></div></section>
	<section class="seef-section seef-values-section"><div class="seef-shell"><div class="seef-section-heading"><div><p class="seef-eyebrow">02 — <?php esc_html_e( 'Nos valeurs', 'seef-store' ); ?></p><h2><?php esc_html_e( 'Quatre principes, une même exigence.', 'seef-store' ); ?></h2></div></div><div class="seef-value-grid">
		<article><b><?php esc_html_e( 'Clarté', 'seef-store' ); ?></b><p><?php esc_html_e( 'Des informations lisibles, des prix nets et aucun mécanisme trompeur.', 'seef-store' ); ?></p></article><article><b><?php esc_html_e( 'Durabilité', 'seef-store' ); ?></b><p><?php esc_html_e( 'Des matériaux et des usages imaginés pour traverser les saisons.', 'seef-store' ); ?></p></article><article><b><?php esc_html_e( 'Simplicité', 'seef-store' ); ?></b><p><?php esc_html_e( 'Chaque interaction a une raison d’être, du menu au checkout.', 'seef-store' ); ?></p></article><article><b><?php esc_html_e( 'Attention', 'seef-store' ); ?></b><p><?php esc_html_e( 'Un design accessible qui respecte le rythme et les préférences de chacun.', 'seef-store' ); ?></p></article>
	</div></div></section>
	<section class="seef-mission"><div class="seef-shell seef-mission-grid" data-reveal><article><span>03</span><h2><?php esc_html_e( 'Notre mission', 'seef-store' ); ?></h2><p><?php esc_html_e( 'Faire gagner du temps grâce à une sélection cohérente et une expérience d’achat immédiatement compréhensible.', 'seef-store' ); ?></p></article><article><span>04</span><h2><?php esc_html_e( 'Notre vision', 'seef-store' ); ?></h2><p><?php esc_html_e( 'Créer une boutique expressive, rapide et rassurante, sans jamais perdre la simplicité qui guide chaque choix.', 'seef-store' ); ?></p></article></div></section>
	<section class="seef-section"><div class="seef-shell seef-stats" data-reveal><div><b>16</b><span><?php esc_html_e( 'produits soigneusement présentés', 'seef-store' ); ?></span></div><div><b>4</b><span><?php esc_html_e( 'univers complémentaires', 'seef-store' ); ?></span></div><div><b>3</b><span><?php esc_html_e( 'langues prises en charge', 'seef-store' ); ?></span></div><div><b>2</b><span><?php esc_html_e( 'modes visuels', 'seef-store' ); ?></span></div></div></section>
	<section class="seef-cta"><div class="seef-shell"><h2><?php esc_html_e( 'Prêt à explorer la sélection ?', 'seef-store' ); ?></h2><a class="seef-button seef-button--light" href="<?php echo esc_url( wc_get_page_permalink( 'shop' ) ); ?>"><?php esc_html_e( 'Découvrir la boutique', 'seef-store' ); ?> →</a></div></section>
</main>
<?php get_footer(); ?>
