<?php

declare(strict_types=1);

namespace SeefStore\Support;

final class Translator implements Service {
	/** @var array<string,array<string,string>> */
	private array $catalog = array(
		'en_US' => array(
			'Boutique' => 'Shop', 'À propos' => 'About', 'Contact' => 'Contact', 'Accueil' => 'Home', 'Catégories' => 'Categories', 'Aucune catégorie disponible.' => 'No category available.', 'Nouveau' => 'New', 'Sélection 2026' => '2026 selection', 'NEW' => 'NEW',
			'Rechercher des produits…' => 'Search products…', 'Rechercher un produit, une catégorie…' => 'Search for a product or category…', 'Rechercher' => 'Search', 'Mon compte' => 'My account', 'Panier' => 'Cart',
			'Découvrir la boutique' => 'Explore the shop', 'Voir les nouveautés' => 'See what’s new', 'Nos catégories' => 'Our categories',
			'Nouveautés choisies pour vous' => 'New arrivals picked for you', 'Les essentiels SEEF' => 'SEEF essentials',
			'Pourquoi SEEF STORE ?' => 'Why SEEF STORE?', 'Livraison suivie' => 'Tracked delivery', 'Paiement de démonstration sécurisé' => 'Secure demo payment',
			'Retours simplifiés' => 'Easy returns', 'Support humain' => 'Human support', 'Voir tous les produits' => 'View all products',
			'Une boutique pensée pour mieux vivre avec la technologie.' => 'A store designed for a better life with technology.',
			'Notre histoire' => 'Our story', 'Notre mission' => 'Our mission', 'Notre vision' => 'Our vision', 'Nos valeurs' => 'Our values',
			'Écrivez-nous' => 'Write to us', 'Nom complet' => 'Full name', 'Adresse e-mail' => 'Email address', 'Sujet' => 'Subject', 'Message' => 'Message',
			'Envoyer le message' => 'Send message', 'Questions fréquentes' => 'Frequently asked questions', 'Disponibilité' => 'Availability',
			'Filtrer la boutique' => 'Filter shop', 'Toutes les catégories' => 'All categories', 'Prix minimum' => 'Minimum price', 'Prix maximum' => 'Maximum price',
			'En stock uniquement' => 'In stock only', 'Appliquer' => 'Apply', 'Réinitialiser' => 'Reset', 'Produit' => 'Product',
			'Ajouter au panier' => 'Add to cart', 'Newsletter' => 'Newsletter', 'Recevez nos nouveautés et conseils, sans bruit.' => 'Get new arrivals and useful tips, without noise.',
			'Inscription enregistrée — démonstration locale.' => 'Subscription saved — local demo.', 'Saisissez une adresse e-mail valide.' => 'Enter a valid email address.', 'Trop de tentatives. Réessayez dans quelques minutes.' => 'Too many attempts. Try again in a few minutes.', 'L’inscription n’a pas pu être enregistrée.' => 'The subscription could not be saved.', 'S’inscrire' => 'Subscribe',
			'Contenu et témoignages de démonstration.' => 'Demo content and testimonials.', 'Tous droits réservés.' => 'All rights reserved.',
			'Explorer' => 'Explore', 'Votre espace' => 'Your space', 'Commande' => 'Checkout', 'Projet' => 'Project', 'Projet portfolio local — aucune vente réelle.' => 'Local portfolio project — no real sales.',
			'Aller au contenu' => 'Skip to content', 'Livraison offerte dès 1 000 MAD' => 'Free delivery over MAD 1,000', 'Boutique locale de démonstration — aucun paiement réel' => 'Local demo store — no real payment',
			'Ouvrir le menu' => 'Open menu', 'Fermer le menu' => 'Close menu', 'Navigation principale' => 'Primary navigation', 'Navigation de pied de page' => 'Footer navigation', 'Langue' => 'Language', 'Changer le thème' => 'Change theme',
			'Activer le thème clair' => 'Enable light theme', 'Activer le thème sombre' => 'Enable dark theme', 'Articles dans le panier' => 'Items in cart', 'En stock' => 'In stock', 'Rupture de stock' => 'Out of stock',
			'Collection 2026 · Technologie essentielle' => '2026 Collection · Essential technology', 'Moins de bruit.' => 'Less noise.', 'Plus d’essentiel.' => 'More of what matters.',
			'Des objets tech, workspace et lifestyle choisis pour être beaux, intuitifs et réellement utiles au quotidien.' => 'Tech, workspace and lifestyle objects selected to be beautiful, intuitive and genuinely useful every day.',
			'objets sélectionnés' => 'selected objects', 'univers' => 'collections', 'démo locale' => 'local demo', 'Sélection SEEF STORE' => 'SEEF STORE selection', 'Conçu pour votre rythme' => 'Designed for your rhythm', 'Design calme' => 'Quiet design', 'Usage intuitif' => 'Intuitive use',
			'Explorez autrement' => 'Explore differently', 'Nouveautés' => 'New arrivals', 'Des objets qui trouvent naturellement leur place.' => 'Objects that naturally find their place.', 'L’idée SEEF' => 'The SEEF idea',
			'La technologie disparaît quand elle est bien pensée.' => 'Technology disappears when it is well designed.', 'Nous imaginons une sélection où la fonction reste évidente, les matériaux agréables et le design suffisamment sobre pour durer.' => 'We imagine a selection where function stays obvious, materials feel good and design is calm enough to last.', 'Découvrir notre approche' => 'Discover our approach',
			'Sélection' => 'Selection', 'Notre promesse' => 'Our promise', 'Une expérience de livraison claire, avec frais annoncés avant validation.' => 'A clear delivery experience, with costs shown before confirmation.', 'Virement fictif ou paiement à la livraison, sans aucune donnée bancaire réelle.' => 'Demo bank transfer or cash on delivery, without any real banking data.',
			'Un parcours client lisible et des informations faciles à retrouver.' => 'A clear customer journey with easy-to-find information.', 'Chaque demande est validée, enregistrée et consultable par l’administrateur.' => 'Every request is validated, stored and available to the administrator.',
			'Témoignages fictifs' => 'Fictional testimonials', 'Pensé dans les moindres détails' => 'Thought through to the last detail', 'Contenu de démonstration' => 'Demo content', 'profil fictif' => 'fictional profile',
			'Une sélection courte, cohérente et beaucoup plus simple à explorer.' => 'A focused, consistent selection that is much easier to explore.', 'Le parcours d’achat est net, de la fiche produit jusqu’à la commande.' => 'The purchase journey is clear, from product page to checkout.', 'Le mode sombre et la version mobile donnent vraiment envie de parcourir le catalogue.' => 'Dark mode and the mobile experience make browsing the catalog genuinely enjoyable.', 'Une dose d’inspiration, rarement mais bien.' => 'A thoughtful dose of inspiration, only when it matters.',
			'À propos de SEEF STORE' => 'About SEEF STORE', 'Le beau devient utile.' => 'Beauty becomes useful.', 'L’utile devient évident.' => 'Useful becomes effortless.', 'SEEF STORE est une marque fictive créée pour démontrer une expérience WooCommerce complète, humaine et contemporaine.' => 'SEEF STORE is a fictional brand created to demonstrate a complete, human and contemporary WooCommerce experience.',
			'Une sélection née du refus du superflu.' => 'A selection born from rejecting the superfluous.', 'SEEF STORE imagine une autre façon de découvrir les objets du quotidien : moins de références interchangeables, plus de cohérence et une information honnête.' => 'SEEF STORE imagines a different way to discover everyday objects: fewer interchangeable items, more coherence and honest information.',
			'Cette boutique est un projet portfolio local. La marque, les chiffres et les témoignages sont fictifs ; l’architecture e-commerce, les comptes, le panier et les commandes utilisent réellement WordPress et WooCommerce.' => 'This store is a local portfolio project. The brand, figures and testimonials are fictional; its e-commerce architecture, accounts, cart and orders really use WordPress and WooCommerce.',
			'Quatre principes, une même exigence.' => 'Four principles, one standard.', 'Clarté' => 'Clarity', 'Durabilité' => 'Durability', 'Simplicité' => 'Simplicity', 'Attention' => 'Care', 'Des informations lisibles, des prix nets et aucun mécanisme trompeur.' => 'Readable information, clear prices and no deceptive patterns.', 'Des matériaux et des usages imaginés pour traverser les saisons.' => 'Materials and uses imagined to last through the seasons.', 'Chaque interaction a une raison d’être, du menu au checkout.' => 'Every interaction has a purpose, from menu to checkout.', 'Un design accessible qui respecte le rythme et les préférences de chacun.' => 'Accessible design that respects everyone’s pace and preferences.',
			'Faire gagner du temps en réunissant des produits fictifs cohérents dans une expérience d’achat réellement fonctionnelle.' => 'Save time by bringing coherent fictional products into a genuinely functional shopping experience.', 'Montrer qu’une boutique WordPress peut être expressive, rapide, maintenable et sûre sans perdre sa simplicité.' => 'Show that a WordPress store can be expressive, fast, maintainable and secure without losing simplicity.', 'produits fictifs détaillés' => 'detailed fictional products', 'univers complémentaires' => 'complementary collections', 'langues prises en charge' => 'supported languages', 'modes visuels' => 'visual modes', 'Prêt à explorer la sélection ?' => 'Ready to explore the selection?',
			'Parlons de ce qui compte.' => 'Let’s talk about what matters.', 'Une question sur la démonstration, une commande locale ou le fonctionnement de la boutique ? Écrivez-nous.' => 'A question about the demo, a local order or how the store works? Write to us.', 'Nous vous répondons avec clarté.' => 'We answer clearly.', 'Le formulaire est relié au backend WordPress. Chaque message validé est enregistré dans MariaDB et visible uniquement par un administrateur autorisé.' => 'The form is connected to WordPress. Every validated message is stored in MariaDB and visible only to an authorized administrator.',
			'Lundi–vendredi, 09:00–18:00 (horaires fictifs)' => 'Monday–Friday, 09:00–18:00 (fictional hours)', 'Délai indicatif' => 'Typical response time', 'Sous un jour ouvré — démonstration' => 'Within one business day — demo', 'Confidentialité' => 'Privacy', 'N’envoyez aucune donnée sensible dans cet environnement local.' => 'Do not send sensitive data in this local environment.', 'Aide rapide' => 'Quick help',
			'Puis-je effectuer un vrai paiement ?' => 'Can I make a real payment?', 'Non. Cette boutique locale utilise uniquement des moyens de paiement de démonstration et ne doit recevoir aucune donnée bancaire réelle.' => 'No. This local store only uses demo payment methods and must not receive real banking data.', 'Les produits peuvent-ils être commandés ?' => 'Can products be ordered?', 'Le checkout crée de vraies commandes WooCommerce en base locale, mais les produits et livraisons restent entièrement fictifs.' => 'Checkout creates real WooCommerce orders locally, but products and deliveries remain entirely fictional.', 'Où retrouver mes commandes ?' => 'Where can I find my orders?', 'Connectez-vous à Mon compte puis ouvrez la section Commandes.' => 'Sign in to My account and open Orders.', 'Mon message est-il réellement conservé ?' => 'Is my message really stored?', 'Oui, après validation et contrôle anti-spam il est stocké comme ressource privée dans WordPress/MariaDB.' => 'Yes. After validation and anti-spam checks, it is stored as a private WordPress/MariaDB resource.',
			'Paiement de démonstration sans données bancaires réelles' => 'Demo payment without real banking data', 'Livraison suivie au Maroc' => 'Tracked delivery in Morocco', 'Assistance via le formulaire sécurisé' => 'Support through the secure form',
			'Cette page s’est égarée.' => 'This page wandered off.', 'Revenez à l’accueil ou poursuivez votre exploration dans la boutique.' => 'Return home or continue exploring the shop.', 'Retour à l’accueil' => 'Back to home', 'Aucun contenu trouvé.' => 'No content found.',
			'Merci ! Votre message a bien été enregistré.' => 'Thank you! Your message has been saved.', 'Certains champs doivent être corrigés.' => 'Some fields need to be corrected.', 'La vérification de sécurité a échoué. Rechargez la page.' => 'Security verification failed. Reload the page.', 'Trop de messages ont été envoyés. Réessayez dans quelques minutes.' => 'Too many messages were sent. Try again in a few minutes.', 'Le message n’a pas pu être enregistré.' => 'The message could not be saved.',
			'expérience fluide' => 'smooth experience', 'Commande en toute sérénité' => 'Order with confidence', 'Un parcours de démonstration sécurisé, sans collecte de données bancaires réelles.' => 'A secure demo journey without collecting real banking details.',
			'Expérience client' => 'Customer experience', 'Scénarios illustratifs — projet démo' => 'Illustrative scenarios — demo project', 'Une sélection contemporaine qui place la simplicité, la qualité d’usage et la clarté au premier plan.' => 'A contemporary selection putting simplicity, usability and clarity first.',
			'Cette vitrine portfolio met en scène une marque fictive dans une expérience e-commerce complète, du catalogue au suivi des commandes.' => 'This portfolio storefront presents a fictional brand through a complete e-commerce experience, from catalog to order tracking.',
			'Faire gagner du temps grâce à une sélection cohérente et une expérience d’achat immédiatement compréhensible.' => 'Save time through a coherent selection and an instantly understandable shopping experience.', 'Créer une boutique expressive, rapide et rassurante, sans jamais perdre la simplicité qui guide chaque choix.' => 'Create an expressive, fast and reassuring store without losing the simplicity behind every choice.', 'produits soigneusement présentés' => 'carefully presented products',
			'Service client' => 'Customer care', 'Une question sur un produit, une commande ou votre expérience ? Notre équipe est à votre écoute.' => 'A question about a product, an order or your experience? Our team is here to help.', 'Votre demande est contrôlée et conservée de façon privée afin que notre équipe puisse assurer son suivi.' => 'Your request is validated and kept private so our team can follow it up.',
			'Lundi–vendredi, 09:00–18:00' => 'Monday–Friday, 09:00–18:00', 'Sous un jour ouvré' => 'Within one business day', 'N’envoyez aucune donnée personnelle ou bancaire sensible.' => 'Do not send sensitive personal or banking information.',
			'Non. Cette vitrine utilise uniquement des moyens de paiement de démonstration et ne doit recevoir aucune donnée bancaire réelle.' => 'No. This storefront only uses demo payment methods and must not receive real banking data.', 'Le parcours permet de tester une commande complète, mais les produits et les livraisons restent fictifs.' => 'The journey lets you test a complete order, but products and deliveries remain fictional.', 'Oui. Après validation et contrôle anti-spam, il reste privé et accessible uniquement à l’administrateur.' => 'Yes. After validation and anti-spam checks, it remains private and is accessible only to the administrator.',
			'Expérience e-commerce de démonstration — aucun paiement réel' => 'Demo e-commerce experience — no real payment', 'Portfolio' => 'Portfolio', 'Expérience e-commerce conçue avec WordPress et WooCommerce.' => 'E-commerce experience built with WordPress and WooCommerce.', 'Projet portfolio — démonstration sans vente réelle.' => 'Portfolio project — demo with no real sales.',
			'Découvrez la sélection SEEF STORE : technologie, accessoires, espace de travail et objets lifestyle pensés pour le quotidien.' => 'Discover the SEEF STORE selection: technology, accessories, workspace and lifestyle objects designed for everyday life.', 'Découvrez notre sélection %s, choisie pour son design et sa simplicité d’usage.' => 'Discover our %s selection, chosen for its design and ease of use.',
		),
		'ar' => array(
			'Boutique' => 'المتجر', 'À propos' => 'من نحن', 'Contact' => 'اتصل بنا', 'Accueil' => 'الرئيسية', 'Catégories' => 'الفئات', 'Aucune catégorie disponible.' => 'لا توجد فئات متاحة.', 'Nouveau' => 'جديد', 'Sélection 2026' => 'مختارات 2026', 'NEW' => 'جديد',
			'Rechercher des produits…' => 'ابحث عن المنتجات…', 'Rechercher un produit, une catégorie…' => 'ابحث عن منتج أو فئة…', 'Rechercher' => 'بحث', 'Mon compte' => 'حسابي', 'Panier' => 'السلة',
			'Découvrir la boutique' => 'اكتشف المتجر', 'Voir les nouveautés' => 'شاهد الجديد', 'Nos catégories' => 'فئاتنا',
			'Nouveautés choisies pour vous' => 'وصل حديثاً من أجلك', 'Les essentiels SEEF' => 'أساسيات SEEF',
			'Pourquoi SEEF STORE ?' => 'لماذا SEEF STORE؟', 'Livraison suivie' => 'توصيل مع التتبع', 'Paiement de démonstration sécurisé' => 'دفع تجريبي آمن',
			'Retours simplifiés' => 'إرجاع مبسط', 'Support humain' => 'دعم بشري', 'Voir tous les produits' => 'عرض كل المنتجات',
			'Une boutique pensée pour mieux vivre avec la technologie.' => 'متجر مصمم لحياة أفضل مع التكنولوجيا.',
			'Notre histoire' => 'قصتنا', 'Notre mission' => 'مهمتنا', 'Notre vision' => 'رؤيتنا', 'Nos valeurs' => 'قيمنا',
			'Écrivez-nous' => 'راسلنا', 'Nom complet' => 'الاسم الكامل', 'Adresse e-mail' => 'البريد الإلكتروني', 'Sujet' => 'الموضوع', 'Message' => 'الرسالة',
			'Envoyer le message' => 'إرسال الرسالة', 'Questions fréquentes' => 'الأسئلة الشائعة', 'Disponibilité' => 'التوفر',
			'Filtrer la boutique' => 'تصفية المتجر', 'Toutes les catégories' => 'كل الفئات', 'Prix minimum' => 'السعر الأدنى', 'Prix maximum' => 'السعر الأقصى',
			'En stock uniquement' => 'المتوفر فقط', 'Appliquer' => 'تطبيق', 'Réinitialiser' => 'إعادة ضبط', 'Produit' => 'منتج',
			'Ajouter au panier' => 'أضف إلى السلة', 'Newsletter' => 'النشرة البريدية', 'Recevez nos nouveautés et conseils, sans bruit.' => 'استقبل جديدنا ونصائحنا المفيدة.',
			'Inscription enregistrée — démonstration locale.' => 'تم حفظ الاشتراك — تجربة محلية.', 'Saisissez une adresse e-mail valide.' => 'أدخل عنوان بريد إلكتروني صالحاً.', 'Trop de tentatives. Réessayez dans quelques minutes.' => 'محاولات كثيرة. أعد المحاولة بعد بضع دقائق.', 'L’inscription n’a pas pu être enregistrée.' => 'تعذر حفظ الاشتراك.', 'S’inscrire' => 'اشترك',
			'Contenu et témoignages de démonstration.' => 'محتوى وشهادات تجريبية.', 'Tous droits réservés.' => 'جميع الحقوق محفوظة.',
			'Explorer' => 'استكشف', 'Votre espace' => 'مساحتك', 'Commande' => 'إتمام الطلب', 'Projet' => 'المشروع', 'Projet portfolio local — aucune vente réelle.' => 'مشروع أعمال محلي — لا توجد مبيعات حقيقية.',
			'Aller au contenu' => 'انتقل إلى المحتوى', 'Livraison offerte dès 1 000 MAD' => 'توصيل مجاني ابتداءً من 1000 درهم', 'Boutique locale de démonstration — aucun paiement réel' => 'متجر تجريبي محلي — لا يوجد دفع حقيقي', 'Ouvrir le menu' => 'فتح القائمة', 'Fermer le menu' => 'إغلاق القائمة', 'Navigation principale' => 'التنقل الرئيسي', 'Navigation de pied de page' => 'تنقل أسفل الصفحة', 'Langue' => 'اللغة', 'Changer le thème' => 'تغيير المظهر', 'Activer le thème clair' => 'تفعيل الوضع الفاتح', 'Activer le thème sombre' => 'تفعيل الوضع الداكن', 'Articles dans le panier' => 'عناصر السلة', 'En stock' => 'متوفر', 'Rupture de stock' => 'غير متوفر',
			'Collection 2026 · Technologie essentielle' => 'مجموعة 2026 · تكنولوجيا أساسية', 'Moins de bruit.' => 'ضجيج أقل.', 'Plus d’essentiel.' => 'جوهر أكثر.', 'Des objets tech, workspace et lifestyle choisis pour être beaux, intuitifs et réellement utiles au quotidien.' => 'منتجات تقنية ومكتبية ويومية مختارة لتكون جميلة وسهلة ومفيدة فعلاً.', 'objets sélectionnés' => 'منتجاً مختاراً', 'univers' => 'مجموعات', 'démo locale' => 'تجربة محلية', 'Sélection SEEF STORE' => 'مختارات SEEF STORE', 'Conçu pour votre rythme' => 'مصمم لإيقاعك', 'Design calme' => 'تصميم هادئ', 'Usage intuitif' => 'استخدام بديهي',
			'Explorez autrement' => 'استكشف بطريقة مختلفة', 'Nouveautés' => 'وصل حديثاً', 'Des objets qui trouvent naturellement leur place.' => 'منتجات تجد مكانها بشكل طبيعي.', 'L’idée SEEF' => 'فكرة SEEF', 'La technologie disparaît quand elle est bien pensée.' => 'تختفي التكنولوجيا حين يكون تصميمها جيداً.', 'Nous imaginons une sélection où la fonction reste évidente, les matériaux agréables et le design suffisamment sobre pour durer.' => 'نختار منتجات واضحة الوظيفة ومريحة المواد وهادئة التصميم لتدوم.', 'Découvrir notre approche' => 'اكتشف نهجنا', 'Sélection' => 'مختارات', 'Notre promesse' => 'وعدنا',
			'Une expérience de livraison claire, avec frais annoncés avant validation.' => 'تجربة توصيل واضحة مع عرض الرسوم قبل التأكيد.', 'Virement fictif ou paiement à la livraison, sans aucune donnée bancaire réelle.' => 'تحويل تجريبي أو دفع عند التسليم دون أي بيانات مصرفية حقيقية.', 'Un parcours client lisible et des informations faciles à retrouver.' => 'رحلة شراء واضحة ومعلومات يسهل العثور عليها.', 'Chaque demande est validée, enregistrée et consultable par l’administrateur.' => 'يتم التحقق من كل طلب وحفظه وإتاحته للمشرف.',
			'Témoignages fictifs' => 'شهادات خيالية', 'Pensé dans les moindres détails' => 'مدروس حتى أدق التفاصيل', 'Contenu de démonstration' => 'محتوى تجريبي', 'profil fictif' => 'ملف خيالي', 'Une sélection courte, cohérente et beaucoup plus simple à explorer.' => 'مجموعة مركزة ومتناسقة وسهلة الاستكشاف.', 'Le parcours d’achat est net, de la fiche produit jusqu’à la commande.' => 'مسار شراء واضح من صفحة المنتج حتى الطلب.', 'Le mode sombre et la version mobile donnent vraiment envie de parcourir le catalogue.' => 'الوضع الداكن وتجربة الهاتف يجعلان تصفح الكتالوج ممتعاً.', 'Une dose d’inspiration, rarement mais bien.' => 'جرعة مختارة من الإلهام في الوقت المناسب.',
			'À propos de SEEF STORE' => 'عن SEEF STORE', 'Le beau devient utile.' => 'الجمال يصبح مفيداً.', 'L’utile devient évident.' => 'والمفيد يصبح بديهياً.', 'SEEF STORE est une marque fictive créée pour démontrer une expérience WooCommerce complète, humaine et contemporaine.' => 'SEEF STORE علامة خيالية لعرض تجربة WooCommerce متكاملة وإنسانية ومعاصرة.', 'Une sélection née du refus du superflu.' => 'مختارات ولدت من رفض الزائد.', 'SEEF STORE imagine une autre façon de découvrir les objets du quotidien : moins de références interchangeables, plus de cohérence et une information honnête.' => 'يقدم SEEF STORE طريقة مختلفة لاكتشاف منتجات الحياة اليومية: خيارات أقل تشابهاً واتساق أكبر ومعلومات صادقة.', 'Cette boutique est un projet portfolio local. La marque, les chiffres et les témoignages sont fictifs ; l’architecture e-commerce, les comptes, le panier et les commandes utilisent réellement WordPress et WooCommerce.' => 'هذا المتجر مشروع أعمال محلي. العلامة والأرقام والشهادات خيالية، لكن البنية والحسابات والسلة والطلبات تستخدم WordPress وWooCommerce فعلياً.',
			'Quatre principes, une même exigence.' => 'أربعة مبادئ ومعيار واحد.', 'Clarté' => 'الوضوح', 'Durabilité' => 'الاستدامة', 'Simplicité' => 'البساطة', 'Attention' => 'العناية', 'Des informations lisibles, des prix nets et aucun mécanisme trompeur.' => 'معلومات مقروءة وأسعار واضحة دون أساليب مضللة.', 'Des matériaux et des usages imaginés pour traverser les saisons.' => 'مواد واستخدامات مصممة لتدوم عبر المواسم.', 'Chaque interaction a une raison d’être, du menu au checkout.' => 'لكل تفاعل سبب، من القائمة إلى إتمام الطلب.', 'Un design accessible qui respecte le rythme et les préférences de chacun.' => 'تصميم سهل الوصول يحترم إيقاع وتفضيلات الجميع.',
			'Faire gagner du temps en réunissant des produits fictifs cohérents dans une expérience d’achat réellement fonctionnelle.' => 'توفير الوقت بجمع منتجات خيالية متناسقة في تجربة شراء فعالة حقاً.', 'Montrer qu’une boutique WordPress peut être expressive, rapide, maintenable et sûre sans perdre sa simplicité.' => 'إظهار أن متجر WordPress يمكن أن يكون سريعاً وآمناً وسهل الصيانة دون فقدان بساطته.', 'produits fictifs détaillés' => 'منتجاً خيالياً مفصلاً', 'univers complémentaires' => 'مجموعات متكاملة', 'langues prises en charge' => 'لغات مدعومة', 'modes visuels' => 'وضعان للعرض', 'Prêt à explorer la sélection ?' => 'هل أنت مستعد لاستكشاف المختارات؟',
			'Parlons de ce qui compte.' => 'لنتحدث عما يهم.', 'Une question sur la démonstration, une commande locale ou le fonctionnement de la boutique ? Écrivez-nous.' => 'لديك سؤال عن التجربة أو طلب محلي أو عمل المتجر؟ راسلنا.', 'Nous vous répondons avec clarté.' => 'نجيبك بوضوح.', 'Le formulaire est relié au backend WordPress. Chaque message validé est enregistré dans MariaDB et visible uniquement par un administrateur autorisé.' => 'النموذج متصل بخلفية WordPress. تُحفظ كل رسالة صالحة في MariaDB ولا يراها إلا مشرف مخول.', 'Lundi–vendredi, 09:00–18:00 (horaires fictifs)' => 'الاثنين–الجمعة، 09:00–18:00 (أوقات خيالية)', 'Délai indicatif' => 'مدة الرد المتوقعة', 'Sous un jour ouvré — démonstration' => 'خلال يوم عمل — تجربة', 'Confidentialité' => 'الخصوصية', 'N’envoyez aucune donnée sensible dans cet environnement local.' => 'لا ترسل أي بيانات حساسة في هذه البيئة المحلية.', 'Aide rapide' => 'مساعدة سريعة',
			'Puis-je effectuer un vrai paiement ?' => 'هل يمكنني إجراء دفع حقيقي؟', 'Non. Cette boutique locale utilise uniquement des moyens de paiement de démonstration et ne doit recevoir aucune donnée bancaire réelle.' => 'لا. يستخدم هذا المتجر المحلي وسائل دفع تجريبية فقط ولا يجب أن يتلقى بيانات مصرفية حقيقية.', 'Les produits peuvent-ils être commandés ?' => 'هل يمكن طلب المنتجات؟', 'Le checkout crée de vraies commandes WooCommerce en base locale, mais les produits et livraisons restent entièrement fictifs.' => 'ينشئ إتمام الطلب طلبات WooCommerce حقيقية محلياً، لكن المنتجات والتوصيل خيالية بالكامل.', 'Où retrouver mes commandes ?' => 'أين أجد طلباتي؟', 'Connectez-vous à Mon compte puis ouvrez la section Commandes.' => 'سجل الدخول إلى حسابي ثم افتح قسم الطلبات.', 'Mon message est-il réellement conservé ?' => 'هل يتم حفظ رسالتي فعلاً؟', 'Oui, après validation et contrôle anti-spam il est stocké comme ressource privée dans WordPress/MariaDB.' => 'نعم، بعد التحقق ومكافحة الرسائل المزعجة تُحفظ كمورد خاص في WordPress/MariaDB.',
			'Paiement de démonstration sans données bancaires réelles' => 'دفع تجريبي دون بيانات مصرفية حقيقية', 'Livraison suivie au Maroc' => 'توصيل متتبع داخل المغرب', 'Assistance via le formulaire sécurisé' => 'دعم عبر النموذج الآمن', 'Cette page s’est égarée.' => 'هذه الصفحة ضلت طريقها.', 'Revenez à l’accueil ou poursuivez votre exploration dans la boutique.' => 'عد إلى الرئيسية أو تابع استكشاف المتجر.', 'Retour à l’accueil' => 'العودة إلى الرئيسية', 'Aucun contenu trouvé.' => 'لم يتم العثور على محتوى.',
			'Merci ! Votre message a bien été enregistré.' => 'شكراً! تم حفظ رسالتك.', 'Certains champs doivent être corrigés.' => 'بعض الحقول تحتاج إلى تصحيح.', 'La vérification de sécurité a échoué. Rechargez la page.' => 'فشل التحقق الأمني. أعد تحميل الصفحة.', 'Trop de messages ont été envoyés. Réessayez dans quelques minutes.' => 'تم إرسال رسائل كثيرة. حاول بعد بضع دقائق.', 'Le message n’a pas pu être enregistré.' => 'تعذر حفظ الرسالة.',
			'expérience fluide' => 'تجربة سلسة', 'Commande en toute sérénité' => 'اطلب بكل ثقة', 'Un parcours de démonstration sécurisé, sans collecte de données bancaires réelles.' => 'تجربة طلب آمنة دون جمع بيانات مصرفية حقيقية.',
			'Expérience client' => 'تجربة العميل', 'Scénarios illustratifs — projet démo' => 'سيناريوهات توضيحية — مشروع تجريبي', 'Une sélection contemporaine qui place la simplicité, la qualité d’usage et la clarté au premier plan.' => 'تشكيلة معاصرة تضع البساطة وسهولة الاستخدام والوضوح في المقدمة.',
			'Cette vitrine portfolio met en scène une marque fictive dans une expérience e-commerce complète, du catalogue au suivi des commandes.' => 'يعرض هذا المتجر علامة خيالية ضمن تجربة تجارة إلكترونية متكاملة من الكتالوج إلى تتبع الطلبات.',
			'Faire gagner du temps grâce à une sélection cohérente et une expérience d’achat immédiatement compréhensible.' => 'توفير الوقت عبر تشكيلة متناسقة وتجربة شراء سهلة الفهم.', 'Créer une boutique expressive, rapide et rassurante, sans jamais perdre la simplicité qui guide chaque choix.' => 'إنشاء متجر مميز وسريع وموثوق مع الحفاظ على البساطة في كل اختيار.', 'produits soigneusement présentés' => 'منتجاً مقدماً بعناية',
			'Service client' => 'خدمة العملاء', 'Une question sur un produit, une commande ou votre expérience ? Notre équipe est à votre écoute.' => 'لديك سؤال عن منتج أو طلب أو تجربتك؟ فريقنا جاهز لمساعدتك.', 'Votre demande est contrôlée et conservée de façon privée afin que notre équipe puisse assurer son suivi.' => 'يتم التحقق من طلبك وحفظه بشكل خاص ليتمكن فريقنا من متابعته.',
			'Lundi–vendredi, 09:00–18:00' => 'الاثنين–الجمعة، 09:00–18:00', 'Sous un jour ouvré' => 'خلال يوم عمل', 'N’envoyez aucune donnée personnelle ou bancaire sensible.' => 'لا ترسل معلومات شخصية أو مصرفية حساسة.',
			'Non. Cette vitrine utilise uniquement des moyens de paiement de démonstration et ne doit recevoir aucune donnée bancaire réelle.' => 'لا. تستخدم هذه الواجهة وسائل دفع تجريبية فقط ولا يجب أن تستقبل بيانات مصرفية حقيقية.', 'Le parcours permet de tester une commande complète, mais les produits et les livraisons restent fictifs.' => 'يتيح المسار تجربة طلب كامل، لكن المنتجات والتوصيل يظلان خياليين.', 'Oui. Après validation et contrôle anti-spam, il reste privé et accessible uniquement à l’administrateur.' => 'نعم. بعد التحقق ومكافحة الرسائل المزعجة تبقى الرسالة خاصة ومتاحة للمشرف فقط.',
			'Expérience e-commerce de démonstration — aucun paiement réel' => 'تجربة تجارة إلكترونية تجريبية — لا يوجد دفع حقيقي', 'Portfolio' => 'معرض الأعمال', 'Expérience e-commerce conçue avec WordPress et WooCommerce.' => 'تجربة تجارة إلكترونية مبنية باستخدام WordPress وWooCommerce.', 'Projet portfolio — démonstration sans vente réelle.' => 'مشروع معرض أعمال — تجربة دون مبيعات حقيقية.',
			'Découvrez la sélection SEEF STORE : technologie, accessoires, espace de travail et objets lifestyle pensés pour le quotidien.' => 'اكتشف تشكيلة SEEF STORE من التقنية والإكسسوارات ومنتجات مساحة العمل والحياة اليومية.', 'Découvrez notre sélection %s, choisie pour son design et sa simplicité d’usage.' => 'اكتشف تشكيلة %s المختارة لتصميمها وسهولة استخدامها.',
		),
	);

	public function register(): void {
		add_filter( 'gettext', array( $this, 'translate' ), 10, 3 );
		add_filter( 'nav_menu_item_title', array( $this, 'translate_menu_title' ) );
		add_filter( 'woocommerce_page_title', array( $this, 'translate_page_title' ) );
	}

	public function translate( string $translation, string $text, string $domain ): string {
		if ( ! in_array( $domain, array( 'seef-store', 'seef-store-core' ), true ) ) {
			return $translation;
		}
		$locale = $this->requested_locale();
		return $this->catalog[ $locale ][ $text ] ?? $translation;
	}

	public function translate_menu_title( string $title ): string {
		return $this->localized_value( $title );
	}

	public function translate_page_title( string $title ): string {
		return $this->localized_value( $title );
	}

	private function localized_value( string $text ): string {
		$locale = $this->requested_locale();
		return $this->catalog[ $locale ][ $text ] ?? $text;
	}

	private function requested_locale(): string {
		$language = isset( $_GET['seef_lang'] ) ? $_GET['seef_lang'] : ( $_COOKIE['seef_lang'] ?? '' );
		$key      = is_scalar( $language ) ? sanitize_key( wp_unslash( (string) $language ) ) : '';

		return array( 'fr' => 'fr_FR', 'en' => 'en_US', 'ar' => 'ar' )[ $key ] ?? get_locale();
	}
}
